### ISSUE TITLE
Pressing import returns 404 error

### ISSUE THREAD

**Issue by MvdDonk** [skttl/umbraco-deploy-assistant#3]
Hi, I just installed the package via NuGet but when pressing the **Import** button in the backoffice the ajax calls returns a 404:
![image](https://user-images.githubusercontent.com/2156402/67688127-a4b2bb00-f999-11e9-8c93-0ad97251b9e8.png)

Looking at the controller code it looks like the action "Reimport" is missing:
https://github.com/skttl/umbraco-deploy-assistant/blob/master/src/Our.Umbraco.DeployAssistant/Controllers/DeployController.cs

**Comment by skttl** [comment]
Hi @MvdDonk

Thanks for trying this out. I must have forgot something when preparing for the release. I'll have a new version ready later today :)

**Comment by skttl** [comment]
Hi again

Sorry for the delay. 0.3.0 is out now, with a fix :)
https://github.com/skttl/umbraco-deploy-assistant/releases/tag/v0.3.0
